### ISSUE TITLE
Trying to remove the installation files

### ISSUE THREAD

**Issue by daniil518xd** [Android-PowerUser/Windroid_11#12]
Noticed that my phone has not much free space left, and remembered that i installed Windroid 3 times, as 2 first went problematic (disconnected from server). I have seen that some zips weighted not less than 14 gigs, but i cant find their location using default file mananger. Maybe there is some kind of a termux command to delete everything installed with termux? Maybe there is also a way to remove windroid 11?

**Comment by Android-PowerUser** [comment]
Search in /data/data/com.termux/files/home/ this can access in the AOSP file manager in the menu and then tap on Termux or in storage/emulated/0/Download
