### ISSUE TITLE
Connecting to :1 does not connect to machine

### ISSUE THREAD

**Issue by Ricca665** [Android-PowerUser/Windroid_11#2]
![Screenshot_20230925-132008_RVNC_Viewer.png](https://github.com/Android-PowerUser/Windroid_11/assets/84286914/19a09e91-07c1-447f-8af4-655aeda460e3)

I restarted the machine but nothing

**Comment by Android-PowerUser** [comment]
Try `localhost:1`

**Comment by Android-PowerUser** [comment]
Everything works for me. I used the code to download, install and run it. If you don't provide any further details I will close the issue.
