### ISSUE TITLE
vnc password didn't work

### ISSUE THREAD

**Issue by labananebleue** [Android-PowerUser/Windroid_11#3]
The password for the vnc is not correct and i reach the limit of atemp.![Screenshot_20231031-064939_Termux.png](https://github.com/Android-PowerUser/Windroid_11/assets/112826062/b86e2089-abe1-45e8-84c2-6083c9b6a963)

![Screenshot_20231031-065124_RVNC Viewer.png](https://github.com/Android-PowerUser/Windroid_11/assets/112826062/ebbe4e49-12a3-4488-a3df-5bbbbeb0a94e)

![Screenshot_20231031-065129_RVNC Viewer.png](https://github.com/Android-PowerUser/Windroid_11/assets/112826062/263fe58c-8c8e-4f7e-bbc5-39f5f9387e6c)

**Comment by Android-PowerUser** [comment]
If you don't contribute anything further, I will assume my answer worked and will close this issue soon.
